name: Melon Ticket Checker
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@latest
        with:
          product-id: 211782
          schedule-id: 100003
          seat-id: 1276
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '<@U05PET1FKFT> 달려달려~'
